name: Generate Snake

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Grant permissions for the action to commit to the repository
      contents: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Updated to v4 for best practice

      - name: Generate Snake Animation
        uses: Platane/snk@v3 # Using v3 of the action
        id: snake-gif
        with:
          github_user_name: FRBIE # IMPORTANT: Use your GitHub username
          # Outputs for both GIF and SVG are generated
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg
          # Optionally, you can customize colors like your catppuccin_latte theme
          # color_snake: "#DD4A48" # Example: using your accent color for the snake
          # color_dots: "#D9E0EE,#C6D0F5,#B3BDED,#A0ACE7,#8D9BE0" # Example: catppuccin latte dots

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9 # Updated to v9
        with:
          branch: main # Or your default branch (e.g., master)
          message: 'feat: Generate Contribution Snake'
          # The add-and-commit action will automatically add the generated files
          # if they are in the git staging area, which they will be if created/modified.
          # We ensure the assets directory is part of what's committed.
          add: './assets/*' # Make sure to commit the assets directory
