# .github/workflows/snake.yml

name: Generate Snake

on:
  schedule:
    # 每天 UTC 时间 00:00 运行
    - cron: "0 0 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # 授予 action 向仓库提交内容的权限
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        # 重要修改：使用 Platane/snk@v3 而不是 Platane/snk/svg-only@v3
        # Platane/snk@v3 支持 gif_out_path 和 svg_out_path
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: FRBIE # 确保这是你的 GitHub 用户名
          # 以下参数对于 Platane/snk@v3 是有效的
          gif_out_path: ./assets/github-contribution-grid-snake.gif
          svg_out_path: ./assets/github-contribution-grid-snake.svg
          # (可选) 你可以自定义颜色以匹配你的 catppuccin_latte 主题
          # color_snake: "#DD4A48"
          # color_dots: "#D9E0EE,#C6D0F5,#B3BDED,#A0ACE7,#8D9BE0"
          # 对于 Platane/snk@v3，不需要下面被注释掉的 'outputs' 部分，可以删除
          # outputs:
          #   - dist/github-contribution-grid-snake.svg
          #   - dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          #   - dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          # 'branch' 是 EndBug/add-and-commit@v9 的有效输入
          branch: main # 或者你的默认分支 (例如 master)
          message: 'feat: Generate Contribution Snake'
          # 当上一步成功在 ./assets/ 中创建文件后，这里就能找到它们了
          add: './assets/*'
